### ISSUE TITLE
Unnecessary Comments and print statements

### ISSUE THREAD

**Issue by lucasace** [lucasace/Best11-Fantasycricket#13]
**Describe the issue**
In team.py , there are a lot of uneccessary comment statements, comment string and a few print statements

**Solution**
Remove all such comments. comment strings and all print statements and rememeber to autoformat using [black](https://black.readthedocs.io/en/stable/) 

Note: This is only a first timers issue, PRs from experienced users will be labelled invalid
Comment if you would like to work on it

**Comment by nimendrak** [comment]
I am working on this!

**Comment by lucasace** [comment]
Alright go ahead @nimendrak

**Comment by Hinal-Srivastava** [comment]
Hi! Id like to contribute

**Comment by lucasace** [comment]
Heyy @Hinal-Srivastava , issue has been assigned already,
We have other issues, check those out , there are more issues coming, stay tuned for those as well
